services:
  app:
    container_name: BillTrak
    restart: unless-stopped
    image: ghcr.io/solo-web-works/billtrak:main

    ports:
      - "8888:80" # Map port 8888 on the host to port 80 in the container.  Change the left side to change the host port.

    volumes:
      # Mount the current directory for live development
      # - .:/var/www/html
      - ./data/bills.db:/var/www/html/data/bills.db # Persist SQLite data
